#!/bin/bash
# Update trusted plugins and themes on all WordPress websites

for path in $(cat /usr/local/wp-sites)
do

if test -e $path/wp-config.php; then

  cd $path/html
  site=$(basename $(dirname "$path/html"))

  echo $site

  # Update WordPress
  wp $*

  echo

fi

done

