#!/usr/local/bin/bash
# Shift date backwards by so many seconds

if [ -z $1 ]; then
  echo "Usage chdate <seconds> <file>"
  exit 1
else
  if [ -e $2 ]; then
    for file in "${@:2}"; do
      SetFile -m "$(gdate -d"@$[$(gdate -d"$(GetFileInfo -d $file)" +%s)-$1]" +'%m/%d/%Y %H:%M:%S')" $file
    done
  elif [ -z $2 ]; then
    echo "Usage chdate <seconds> <file>"
    exit 2
  else
    echo "$2: File does not exist"
    exit 3
  fi
fi
