#!/usr/local/bin/bash
#
# Batch pull request for specific repository
#
# 1. Merge starverte:master into mbeall:master
# 2. Merge mbeall:master into starverte:dev
# 3. Merge starverte:dev into starverte:master
#

if [ -d $1 ]
then
  repo=$(basename $1)
  cd $1
  hub pull-request -b mbeall/$repo:master -h starverte/$repo:master -m "Merge from master [ci skip]"
  sleep 1
  hub pull-request -b starverte/$repo:dev -h mbeall/$repo:master -m "Pull request [ci skip]"
  sleep 1
  hub pull-request -b starverte/$repo:master -h starverte/$repo:dev -m "$1 x.x.x"
else
  echo 'Usage git-pr <repo>'
  exit 1
fi

