#!/usr/local/bin/bash
#
# Check for any outdated npm dependencies for all repositories
#

outdated=$(echo /tmp/npmg-outdated-$(date +%Y-%m-%d-%H-%M-%S))

for repo in $(cat ~/.local/npm-repositories)
do
  cd $repo
  echo $(basename $repo) >> $outdated
  npm outdated >> $outdated
  echo >> $outdated
done

less $outdated

