#!/usr/local/bin/bash
#
# Install npm dependencies on all repositories
#

status=$(echo /tmp/npm-install-$(date +%Y-%m-%d-%H-%M-%S))

for repo in $(cat /Users/mbeall/.local/npm-repositories | grep mbeall)
do
  cd $repo
  echo $(basename $repo) >> $status
  npm install >> $status
  npm update >> $status
  echo >> $status
done

less $status

